config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  root "home#index"
  devise_for :users
  resources :bloggers do   
    resources :likes
    resources :comments
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  	mount_uploader :blog_image, AvatarUploader
	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 10 }
	has_rich_text :body
  	belongs_to :user
	has_many :likes
	has_many :comments, as: :commentable, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :blogger
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blogger
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :bloggers, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :address, :contact, :dob, :avatar ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :address, :contact, :dob, :avatar], except: [:email])
  end
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  
  def index
    @bloggers = Blogger.all
  end

  def show
    @blogger = Blogger.find(params[:id])
  end

  def new
    @blogger = current_user.bloggers.new
  end

  def create
    @blogger = current_user.bloggers.new(blogger_params)
    if @blogger.save
      redirect_to @blogger
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blogger = Blogger.find(params[:id])
  end

  def update
    @blogger = Blogger.find(params[:id])
    if @blogger.update(blogger_params)
      redirect_to @blogger
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blogger = Blogger.find(params[:id])
    @blogger.destroy
    redirect_to root_path, status: :see_other
  end

  private
    def blogger_params
      params.require(:blogger).permit(:title, :body, :blog_image)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #befor_action :authenticate_user!

  def create 
    @blogger = Blogger.find(params[:blogger_id])
    @comment = @blogger.comments.create(comment_params)
    redirect_to blogger_path(@blogger)
  end

  def destroy
    @blogger = Blogger.find(params[:blogger_id])
    @comment = @blogger.comments.find(params[:id])
    @comment.destroy
    redirect_to blogger_path(@blogger), status: 303
  end

  private 

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blogger.order(created_at: :asc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_blogger
    before_action :find_like, only: [:destroy]
  def create
    if already_liked?
        flash[:notice] = "You can't like more than once"
    else
    @blogger.likes.create(user_id: current_user.id)
    end
    redirect_to blogger_path(@blogger)
  end
  def already_liked?
    Like.where(user_id: current_user.id, blogger_id:
    params[:blogger_id]).exists?
  end
  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to blogger_path(@blogger)
  end
  def find_like
    @like = @blogger.likes.find(params[:id])
 end
  private
  def find_blogger
    @blogger = Blogger.find(params[:blogger_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def user_image
		current_user.avatar.url rescue "https://picsum.photos/200/300"
	end

  def blog_owner(blog)
    current_user.id == blog.user_id
  end

end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bloggers/_form.html.erb
<h1>Write a new blog</h1>
<%= form_with model: @blogger do |form| %>
  <table class="first2">
    <tr>
      <th><%= form.label :title %> </th>
      <td><%= form.text_field :title %> </td>
    </tr>
  </br>
  </br>
    <tr>
      <th><%= form.label :body %><br> </th>
      <td><%= form.rich_text_area :body %> </td>
    </tr>
    <tr>
      <th><%= form.label :image %><br> </th>
      <td><%= form.file_field :blog_image %></td>
    </tr>
    <tr>
      <td><%= form.submit %></td>
    </tr>
  </table>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Edit blogs</h1>

<%= render "form", blogger: @blogger %>

app/views/bloggers/index.html.erb
<table class="table1">
  <% @bloggers.each do |blogger| %>

  <tr class="tr1">
    <th>Title</th>
    <th>body</th>
    <th>Action</th>
  </tr>
  <tr class="tr1">
    <td><%= link_to blogger.title, blogger %></td>
    <td><%= blogger.body %></td>
    <td><%= link_to "Show", blogger %></td>
  </tr>
  <% end %>
</table>
<%= link_to "New blog", new_blogger_path %>
<p><%#= blogger.likes.count %> <%#= (blogger.likes.count) == 1 ? 'Like' : 'Likes'%></p>

app/views/bloggers/new.html.erb
<%= render "form", blogger: @blogger %>

app/views/bloggers/show.html.erb
<%= social_share_button_tag(@blogger.title) %>

<p><%= @blogger.likes.count %> <%= (@blogger.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<% pre_like = @blogger.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to 'Unlike', blogger_like_path(@blogger, pre_like), method: :delete %>
<% else %>
  <%= button_to 'Like', blogger_likes_path(@blogger), method: :post %>
<% end %>

<h3>comment</h3>
  <% @blogger.comments.each do |comment| %>
  <div class="well">
    <%= comment.body %>
      <p>
  <%= link_to "Destroy Comment", "#" %>
</p>
  </div>
  <%end%>


  <%= form_with model: [ @blogger, @blogger.comments.build ] do |form| %>
  <p>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>


<body>
  <div class="wrapper">
    <%= image_tag @blogger.blog_image.url, class: 'blog-show-image' %>
    <h1><%= @blogger.title %></h1>
    <section>
      <p><%= @blogger.body %></p>
    </section>
  </div>
</body>



<style type="text/css">
  @import url('https://fonts.googleapis.com/css?family=Roboto+Slab');
  @import url('https://fonts.googleapis.com/css?family=Montserrat|Rubik+Mono+One');
  body{
    font-family: 'Rubik Mono One', sans-serif; 
    font-family: 'Roboto Slab', serif;
    background-color: #fffff;
    color: #363636;
  }
  .wrapper{
    padding: 0 0 0 0;
    padding: 0 12% 0 12%;
    display:inline-block;
  }
  .blog-show-image{
    width: 1000px;
    height: 500px;
    margin-top: 10px;
    border: 10px solid #000;
  }
  h1{
    font-size: 70px;
    text-align: center;
  }
  .title{
  padding-top: 2rem;
  color:#4C74C9;
    font-size: var(--s2);
  }
  .nav h2{
    padding-left: 7%;
    font-size: var(--s1);
  }
  p{
  line-height: 2rem;
  }
  span{
    color:#00a1e1;
  }
</style>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/home/_current_user_blogs.html.erb
<div class="row">
  <% @blogs.each do |blog| %>
  	<div class="col-12 col-sm-6 col-md-4 image-grid-item">
  		<div style="background-image: url(<%= blog.blog_image.url %>);" class="entry-cover image-grid-cover has-image">
  			<a href="<%= blogger_path(blog) %>" class="image-grid-clickbox"></a>
        <a href="<%= blogger_path(blog) %>" class="cover-wrapper"><%= blog.title %></a>
        <% if blog_owner(blog) %>
          <%= link_to "<i class='fa fa-trash'></i>".html_safe, blogger_path(blog), class: "cover-wrapper trash", title: 'Delete',
            data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }
          %>
          <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_blogger_path(blog), class: "cover-wrapper edit", title: 'Edit' %>
        <%end%>
  		</div>
  	</div>
  <% end %>
</div>
<style type="text/css">
  a.cover-wrapper.trash {
    top: 126px;
    float: left;
    left: 5px;
  }
  a.cover-wrapper.edit {
    top: 125px;
    float: right;
    right: 5px;
  }
</style>

app/views/home/_user_profile.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC -->
        <div class="profile-userpic">
          <%= image_tag user_image, class: "user-image" %>
        </div>
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            <%= current_user&.name %>
          </div>
          <div class="profile-usertitle-job">
            <%= current_user&.email %>
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">
          <a href="tel:<%=current_user&.contact%>" class="btn btn-success btn-sm">Call</a>
          <a href="mailto:<%= current_user&.email %>" class="btn btn-danger btn-sm">Message</a>
          <%= link_to "Edit", edit_user_registration_path, class: "btn btn-warning btn-sm"%>
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
        </div>
        <!-- END MENU -->
        <div class="portlet light bordered">
          <!-- STAT -->
          <div class="row list-separated profile-stat">
            <div class="col-md-4 col-sm-4 col-xs-6">
              <div class="uppercase profile-stat-title"><%= current_user.bloggers.count %></div>
              <div class="uppercase profile-stat-text">Blogs</div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
              <div class="uppercase profile-stat-title">0</div>
              <div class="uppercase profile-stat-text"> Views </div>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
              <div class="uppercase profile-stat-title">0</div>
              <div class="uppercase profile-stat-text">Comments</div>
            </div>
          </div>
          <!-- END STAT -->
          <div>
            <h4 class="profile-desc-title">About <%= current_user&.name %></h4>
            <span class="profile-desc-text"> Lorem ipsum dolor sit amet diam nonummy nibh dolore. </span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">
        <%= render 'current_user_blogs'%>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'user_profile'%>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggingProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<div class="nav_bar">
  <input type="checkbox" id="nav_bar-check">
  <div class="nav_bar-header">
    <div class="nav_bar-title">
      <a class="active" href="/">Blogger</a>
    </div>
  </div>
  <div class="nav_bar-btn">
    <label for="nav_bar-check">
      <span></span>
      <span></span>
      <span></span>
    </label>
  </div>
  
  <div class="nav_bar-links">
    <% if signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= link_to "New Blog", new_blogger_path %>
      <%= link_to "Blogs", bloggers_path %>
      <%= link_to "Logout", destroy_user_session_path,
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } 
      %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %> 
    <% end %>
  </div>
</div>
<style type="text/css">
  * {
  box-sizing: border-box;
}

body {
  margin: 0px;
  font-family: 'segoe ui';
}

.nav_bar {
  height: 50px;
  width: 100%;
  background-color: #4d4d4d;
  position: relative;
}

.nav_bar > .nav_bar-header {
  display: inline;
}

.nav_bar > .nav_bar-header > .nav_bar-title {
  display: inline-block;
  font-size: 22px;
  color: #fff;
  padding: 10px 10px 10px 10px;
}

.nav_bar > .nav_bar-btn {
  display: none;
}

.nav_bar > .nav_bar-links {
  display: inline;
  float: right;
  font-size: 18px;
}

.nav_bar > .nav_bar-links > a {
  display: inline-block;
  padding: 13px 10px 13px 10px;
  text-decoration: none;
  color: #efefef;
}

.nav_bar > .nav_bar-links > a:hover {
  background-color: rgba(0, 0, 0, 0.3);
}

.nav_bar > #nav_bar-check {
  display: none;
}

@media (max-width:600px) {
  .nav_bar > .nav_bar-btn {
    display: inline-block;
    position: absolute;
    right: 0px;
    top: 0px;
  }
  .nav_bar > .nav_bar-btn > label {
    display: inline-block;
    width: 50px;
    height: 50px;
    padding: 13px;
  }
  .nav_bar > .nav_bar-btn > label:hover,.nav_bar  #nav_bar-check:checked ~ .nav_bar-btn > label {
    background-color: rgba(0, 0, 0, 0.3);
  }
  .nav_bar > .nav_bar-btn > label > span {
    display: block;
    width: 25px;
    height: 10px;
    border-top: 2px solid #eee;
  }
  .nav_bar > .nav_bar-links {
    position: absolute;
    display: block;
    width: 100%;
    background-color: #333;
    height: 0px;
    transition: all 0.3s ease-in;
    overflow-y: hidden;
    top: 50px;
    left: 0px;
  }
  .nav_bar > .nav_bar-links > a {
    display: block;
    width: 100%;
  }
  .nav_bar > #nav_bar-check:not(:checked) ~ .nav_bar-links {
    height: 0px;
  }
  .nav_bar > #nav_bar-check:checked ~ .nav_bar-links {
    height: calc(100vh - 50px);
    overflow-y: auto;
  }
}
</style>